CVRP environment created
surana01/jumanji pull request #2
Opened 2022-09-29 15:54 UTC by surana01

Changes Made:
- Added cvrp.md to /docs/ennvironments/
- Added cvrp.md to /docs/api/
- Added register envs to /jumanji/__init__.py
- Created cvrp folder in /jumanji/environments/combinatorial/
- Edited readme.md

2022-09-29 16:47 UTC, alaterre commented on docs/environments/cvrp.md
> +```
I suppose that action `0` corresponds to coming back to the depot?

2022-09-29 16:47 UTC, alaterre commented on jumanji/environments/combinatorial/cvrp/utils.py
> +    Returns the 8 augmentations of a given instance problem described in [1]. This function leverages the existing
We are not super consistent in the codebase, but we should aim to follow the Google Style guide for python: https://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings. For many it's ugly (I like it), but the docstring should respect this format:

"""Start of the docstring
blablabla
"""

2022-09-29 16:47 UTC, alaterre commented on jumanji/environments/combinatorial/cvrp/utils.py
> +    return random.randint(start_key, (), minval=1, maxval=num_nodes + 1)
```suggestion
def generate_start_position(key: PRNGKey, num_nodes: jnp.int32) -> jnp.int32:
    return random.randint(key, (), minval=1, maxval=num_nodes + 1)
```

2022-09-29 16:47 UTC, alaterre commented on jumanji/environments/combinatorial/cvrp/utils.py
> +    return problem
Let's avoid using the same key for two random samplings. 

```suggestion
def generate_problem(key: PRNGKey, num_nodes: jnp.int32) -> Array:
    coord_key, cost_key = jax.random.split(key)
    coords = random.uniform(coord_key, (num_nodes + 1, 2), minval=0, maxval=1)
    costs = random.randint(cost_key, (num_nodes + 1, 1), minval=1, maxval=10)
    problem = jnp.hstack((coords, costs))
    problem = problem.at[DEPOT_IDX, 2].set(0.0)
    return problem
```

2022-09-29 16:47 UTC, alaterre commented on docs/environments/cvrp.md
> +and the depot node, along with the demand of each city.
I understand it must have been more convenient to code. However, I'm not a fan of combining those two values together (coords and cost/demand). The name `problem` is vague. Splitting the array would help to clarify this.

2022-09-29 16:47 UTC, alaterre commented on jumanji/environments/combinatorial/cvrp/utils.py
> +    problem = problem[order, 0:2]
Could we rename this to `tour`?

2022-09-29 16:47 UTC, alaterre commented on jumanji/environments/combinatorial/cvrp/types.py
> +    num_total_visits: number of performed visits (it can count depot multiple times)
I'm not sure I understand the docstring. Is it the number of visits to the depot?

2022-09-29 16:47 UTC, alaterre commented on jumanji/environments/combinatorial/cvrp/env.py
> +        Reinforcement Learning".
Let's find an older reference

2022-09-29 16:47 UTC, alaterre commented on jumanji/environments/combinatorial/cvrp/env.py
> +    def __init__(self, problem_size: int = 20, norm_factor: int = 30):
I don't understand what is `norm_factor` and `MIN_NORM_FACTOR`. Could you add further explanations about it?

2022-09-29 16:47 UTC, alaterre commented on jumanji/environments/combinatorial/cvrp/env.py
> +            f"The cost associated to each node must be lower than 1.0, hence the normalization factor must be "
```suggestion
            "The cost associated with each node must be lower than 1.0, hence the normalization factor must be "
```

2022-09-29 16:47 UTC, alaterre commented on jumanji/environments/combinatorial/cvrp/env.py
> +        return f"CVRP environment with {self.problem_size} nodes and normalization factor {self.norm_factor}."
This is too verbose for a `__repr__`. `CVRP(problem_size=..., norm_factor=...)` is enough

2022-09-29 16:47 UTC, alaterre commented on jumanji/environments/combinatorial/cvrp/env.py
> +             extra: Not used.
```suggestion

```

2022-09-29 16:47 UTC, alaterre commented on jumanji/environments/combinatorial/cvrp/env.py
> +            state, timestep, extra: Tuple[State, TimeStep, Extra] containing the next state of the environment, as well
```suggestion
            state, timestep: Tuple containing the next state of the environment, as well
```

2022-09-29 17:10 UTC, surana01 commented on jumanji/environments/combinatorial/cvrp/types.py
> +    num_total_visits: number of performed visits (it can count depot multiple times)
It's the total number of visits performed which includes visits to both the cities and the depot. Since the depot can be visited multiple times, this var is updated each time the depot is visited. I can update the comment to "num_total_vists: number of performed visits to both cities and depot (it can count depot multiple times)"

2022-09-29 17:15 UTC, surana01 commented on jumanji/environments/combinatorial/cvrp/utils.py
> +    problem = problem[order, 0:2]
In TSP, it is also called "compute_tour_length" so do we want to keep it as is for consistency?

2022-09-30 08:28 UTC, surana01 commented on jumanji/environments/combinatorial/cvrp/env.py
> +        Reinforcement Learning".
Would this work: Toth P., Vigo D. (2014). "Vehicle routing: problems, methods, and applications".

2022-09-30 09:30 UTC, surana01 commented on docs/environments/cvrp.md
> +```
Is the following clearer?

Action space is an `Array` of size equal to the number of city nodes + 1 depot node. The 0th 
index corresponds to the depot node and the remaining indices correspond to the city nodes. A value
of 1 at an index indicates an action to visit the node corresponding to that index, 
a value of 0 indicates an action not to visit that node. 

```
action: [0, 0, 0, 1, 0]  # Problem size of 4 cities, choosing the 3rd city
```

2022-10-03 14:00 UTC, clement-bonnet requested changes
Amazing work! I have a few comments mostly regarding naming, types and design. But overall, great work! :rocket: 
Let me know if you have any questions. I hope I have not bee too silly in my comments.

2022-10-03 14:00 UTC, clement-bonnet commented on jumanji/environments/combinatorial/cvrp/env.py
> +        )
Since Jax>=3.0 (or before, can't remember), the operand argument of `jax.lax.cond` can be unpacked, leading to a more explicit code.
```suggestion
        state = jax.lax.cond(
            is_valid,
            self._update_state,
            lambda _: state,
            state,
            action,
        )
```

2022-10-03 14:00 UTC, clement-bonnet commented on jumanji/environments/combinatorial/cvrp/env.py
> +            shape=(), minimum=0.0, maximum=30.0, dtype=jnp.float32, name="capacity"
I thought the capacity was an integer.

2022-10-03 14:00 UTC, clement-bonnet commented on jumanji/environments/combinatorial/cvrp/env.py
> +            pred=state.visited_mask.sum() == self.problem_size + 1,
With a boolean mask, this would be made easier (and cheaper): `pred=state.visited_mask.all()`

2022-10-03 14:00 UTC, clement-bonnet commented on jumanji/environments/combinatorial/cvrp/env.py
> +            operand=[],
NIT
```suggestion
            operand=None,
```

2022-10-03 14:00 UTC, clement-bonnet commented on jumanji/environments/combinatorial/cvrp/env.py
> +                        1 - is_not_depot) * self.max_capacity,
Could we move the calculation of the capacity before the return statement? It is hard to read in the current state.

2022-10-03 14:00 UTC, clement-bonnet commented on jumanji/environments/combinatorial/cvrp/env.py
> +                        1 - is_not_depot) * self.max_capacity,
Please could we break down this line into multiple lines with intermediate variables? Hard to read

2022-10-03 14:00 UTC, clement-bonnet commented on jumanji/environments/combinatorial/cvrp/env.py
> +            problem=state.problem.at[:, -1].set(jnp.float32(state.problem[:, -1] / self.norm_factor)),
Could we move the normalisation before the return statement? To make it more readable

2022-10-03 14:00 UTC, clement-bonnet commented on jumanji/environments/combinatorial/cvrp/env.py
> +            the coordinates of each node and the depot, and the associated cost (0.0 for the depot)
Would it not make the code more explicit to use a tree instead of an array? E.g. separating city coordinates from their cost. What about the state being the following tree:
- coordinates: jax array (float32) of shape (num_nodes + 1, 2) -> x and y of each ciyt
- demand (or cost?): jax array (I thought costs were int32??) of shape (num_nodes + 1,) -> demand for each city
- position: ...
- capacity: ...
- visited_mask: ...
- order: ...
- num_visits: ...

2022-10-03 14:00 UTC, clement-bonnet commented on jumanji/environments/combinatorial/cvrp/env_test.py
> +from jax import random
Could we not use random from jax which could be confused with random from numpy or even from math (standard library)? Could we please delete this import and use jax.random instead?

2022-10-03 14:00 UTC, clement-bonnet commented on jumanji/environments/combinatorial/cvrp/env_test.py
> +    state, timestep = reset_fn(key)
Could we add a check for compilation here? Check that calling reset twice does not recompile (e.g. if you set one of the input as static). Please see the [BinPack tests](https://github.com/instadeepai/jumanji/blob/main/jumanji/environments/combinatorial/binpack/env_test.py#L136) for instance, for an example of how to do.
```suggestion
    chex.clear_trace_counter()
    reset_fn = jax.jit(chex.assert_max_traces(cvrp_env.reset, n=1))

    key = jax.random.PRNGKey(0)
    state, timestep = reset_fn(key)
    # Call again to check it does not compile twice.
    state, timestep = reset_fn(key)
```

2022-10-03 14:00 UTC, clement-bonnet commented on jumanji/environments/combinatorial/cvrp/env_test.py
> +def test_cvrp__does_not_smoke(cvrp_env: CVRP, capsys: pytest.CaptureFixture) -> None:
Why do we have the capture fixture here?
```suggestion
def test_cvrp__does_not_smoke(cvrp_env: CVRP) -> None:
```

2022-10-03 14:00 UTC, clement-bonnet commented on jumanji/environments/combinatorial/cvrp/env_test.py
> +        assert timestep.step_type < StepType.LAST
We provide `first`, `mid` and `last` methods for that.
```suggestion
        assert not timestep.last()
```

2022-10-03 14:00 UTC, clement-bonnet commented on jumanji/environments/combinatorial/cvrp/env_test.py
> +    assert tour_length == 6.8649917
I guess this works but maybe something like `jnp.is_close` would be safer to use?

2022-10-03 14:00 UTC, clement-bonnet commented on jumanji/environments/combinatorial/cvrp/specs.py
> +        action_mask_obs: specs.BoundedArray,
I am not sure adding `_obs` to each spec is needed here as they all form the `observation_spec`. I would rather add `_spec` as a suffix. What do you think?

2022-10-03 14:00 UTC, clement-bonnet commented on jumanji/environments/combinatorial/cvrp/specs_test.py
> +            self.observation_spec.validate(modified_shape_observation)
The validation should raise an error but not the `_replace`, so I think it is better to move the replace up.
```suggestion
        modified_shape_observation = observation._replace(
            problem=observation.problem[None, ...]
        )
        with pytest.raises(ValueError):
            self.observation_spec.validate(modified_shape_observation)
```

2022-10-03 14:00 UTC, clement-bonnet commented on jumanji/environments/combinatorial/cvrp/specs_test.py
> +        with pytest.raises(ValueError):
Same as above here

2022-10-03 14:00 UTC, clement-bonnet commented on jumanji/environments/combinatorial/cvrp/types.py
> +    capacity: jnp.float32
Since the demand for each node is an integer (e.g. between 1 and 10), why is the capacity a float?

2022-10-03 14:00 UTC, clement-bonnet commented on jumanji/environments/combinatorial/cvrp/utils.py
> +from jax import random
Could we delete this and use `jax.random` instead?

2022-10-03 14:00 UTC, clement-bonnet commented on jumanji/environments/combinatorial/cvrp/utils.py
> +from jumanji.environments.combinatorial.tsp.utils import get_augmentations as get_augmentations_tsp
Same comment here as earlier, if `get_aumentations` is common util to TSP and CVRP, we should have them share the same from a common module and not CVRP import that of TSP.

2022-10-03 14:00 UTC, clement-bonnet commented on jumanji/environments/combinatorial/cvrp/utils.py
> +    costs = random.randint(problem_key, (num_nodes + 1, 1), minval=1, maxval=10)
10 here should be a variable and input to the `generate_problem` function.

2022-10-03 14:02 UTC, clement-bonnet commented on docs/api/environments/cvrp.md
> +::: jumanji.environments.combinatorial.cvrp.env.CVRP
Not link to this line. We need to add CVRP to the `mkdocs.yml` file for the global documentation.

2022-10-03 14:13 UTC, surana01 commented on docs/environments/cvrp.md
> +- `CVRP150-v0`, CVRP problem with 150 nodes with demand (randomly generated).
CVRP 100, 125, and 150 were used in Poppy and so I used the same problem sizes for the registers.

2022-10-03 14:14 UTC, surana01 commented on jumanji/environments/combinatorial/cvrp/env.py
> +    def __init__(self, problem_size: int = 20, norm_factor: int = 30):
Agreed, see the latest commit.

2022-10-04 09:38 UTC, surana01 commented on docs/environments/cvrp.md
> +- **current capacity**: jax array (float32), gives the current capacity of the vehicle.
Yes, it means what the capacity of the vehicle is at the moment, I think current capacity is suitable, but I can change it if others agree it's unclear.

2022-10-04 10:01 UTC, surana01 commented on jumanji/environments/combinatorial/cvrp/env.py
> +            shape=(), minimum=0.0, maximum=30.0, dtype=jnp.float32, name="capacity"
I believe in state: both demands and capacity are integers and in obs: demands and capacity are floats between 0 and 1. I have changed it to this, let me know if this is not suitable.

2022-10-04 14:51 UTC, djbyrne commented on jumanji/environments/combinatorial/cvrp/env.py
> +from jumanji.environments.combinatorial.tsp.utils import compute_tour_length
Yeah I would agree, I think we could probably name it something more generic if it is being used in multiple instances.

2022-10-04 15:21 UTC, ertsiger commented on jumanji/__init__.py
> +register(
For the registered environments, I'd probably provide the maximum demand and capacity following the criteria used in the literature:
* CVRP20 - 30 (see https://arxiv.org/pdf/2010.16011.pdf)
* CVRP50 - 40 (see https://arxiv.org/pdf/2010.16011.pdf)
* CVRP100 - 50 (see Poppy paper)
* CVRP125 - 55 (see Poppy paper)
* CVRP150 - 60 (see Poppy paper)

2022-10-04 15:31 UTC, ertsiger commented on jumanji/environments/combinatorial/cvrp/utils.py
> +
I believe this function used to leverage the analogous one for TSP but it does not anymore. This is how it used to look like:

```
    coord_augmentations = get_augmentations_tsp(problem[:, :2])

    num_nodes = problem.shape[0]
    num_augmentations = coord_augmentations.shape[0]

    costs_per_aug = jnp.tile(problem[:, 2], num_augmentations).reshape(
        num_augmentations, num_nodes, 1
    )
    return jnp.concatenate((coord_augmentations, costs_per_aug), axis=2)
```

Even though coordinates and demands are now separated, I believe it should be possible to call the TSP function for the coordinates alone (thus compressing lines 54-70). I might be wrong though :)

2022-10-04 15:32 UTC, ertsiger commented on jumanji/environments/combinatorial/tsp/utils.py
> -def get_augmentations(problem: Array) -> Array:
I'm not sure why this function has been removed from TSP

2022-10-04 15:33 UTC, surana01 commented on jumanji/environments/combinatorial/tsp/utils.py
> -def get_augmentations(problem: Array) -> Array:
Since TSP did not use this function, it was removed.

2022-10-04 15:34 UTC, surana01 commented on jumanji/__init__.py
> +register(
Makes sense! Just to confirm, all these have max_demand of 10 right? Because the discrete set of d_i is between [1,9].

2022-10-04 15:36 UTC, ertsiger commented on jumanji/environments/combinatorial/tsp/utils.py
> -def get_augmentations(problem: Array) -> Array:
I'd add a test to TSP then similar to the one for CVRP :) We use this function in the Poppy code I believe, so we should keep it.

2022-10-04 16:14 UTC, surana01 commented on jumanji/environments/combinatorial/cvrp/utils.py
> +
Done.

2022-10-04 16:14 UTC, surana01 commented on jumanji/environments/combinatorial/tsp/utils.py
> -def get_augmentations(problem: Array) -> Array:
Done.

2022-10-05 07:13 UTC, ertsiger commented on jumanji/__init__.py
> +register(
Yes, sorry :) Only the maximum capacity set to those quantities and the maximum demand set to 10.

2022-10-05 07:16 UTC, ertsiger commented on docs/environments/cvrp.md
> +- **coordinates**: jax array (float32) of shape (problem_size + 1, 3), shows an array of the coordinates of each city node
I think the coordinates is now an array of (problem_size +1, 2) instead of (problem_size + 1, 2), right?

2022-10-05 07:20 UTC, ertsiger commented on docs/environments/cvrp.md
> +- `CVRP150-v0`, CVRP problem with 150 nodes with demand (randomly generated).
That's correct. For TSP we should add 125 too since it is used in Poppy (it is not really needed since in the refactoring we did we do not use the register but the class constructor directly).

2022-10-05 07:33 UTC, ertsiger commented
I think an `__init__.py`  file similar to those in other environments is missing.

2022-10-05 07:39 UTC, ertsiger commented on jumanji/environments/combinatorial/tsp/utils.py
> -def get_augmentations(problem: Array) -> Array:
I don't see the method restored for TSP and CVRP calling it in the `cvrp_test` branch (maybe the code has not been pushed?).

2022-10-05 07:56 UTC, ertsiger commented on jumanji/environments/combinatorial/cvrp/env_test.py
> +    state, timestep = cvrp_env.step(state, jnp.int32(DEPOT_IDX))
Now that we don't initially choose a node at random, I guess we can remove one of these lines (201 or 202) since line 199 will put as at the depot.

2022-10-05 07:59 UTC, ertsiger commented on jumanji/environments/combinatorial/cvrp/env_test.py
> +def test_tsp__trajectory_action(cvrp_env: CVRP) -> None:
Name should be `test_cvrp` (probably my fault, sorry).

2022-10-05 08:09 UTC, surana01 commented on jumanji/environments/combinatorial/cvrp/env_test.py
> +    state, timestep = cvrp_env.step(state, jnp.int32(DEPOT_IDX))
Agreed.

2022-10-05 08:11 UTC, surana01 commented on jumanji/environments/combinatorial/tsp/utils.py
> -def get_augmentations(problem: Array) -> Array:
Yes sorry, it's pushed now.

2022-10-05 08:17 UTC, ertsiger commented on jumanji/environments/combinatorial/tsp/utils.py
> -def get_augmentations(problem: Array) -> Array:
Just seen the code has been pushed, thanks!

2022-10-05 08:19 UTC, ertsiger commented on jumanji/environments/combinatorial/tsp/utils.py
> -def get_augmentations(problem: Array) -> Array:
I've just seen you have pushed the change, thanks! However, I would place this method in the `utils` of TSP since Poppy imports it from there and it is not generic enough to have it in a more general folder.

2022-10-05 08:20 UTC, ertsiger commented on jumanji/environments/combinatorial/utils.py
> +def get_augmentations(problem: Array) -> Array:
Following the comment in the file above:

I would place this method in the `utils` of TSP (as it was before) since Poppy imports it from there and it is not generic enough to have it in a more general folder.

2022-10-05 08:37 UTC, ertsiger commented
I think everything looks fine now :+1:

2022-10-05 15:20 UTC, clement-bonnet requested changes
Nice work!

2022-10-05 15:20 UTC, clement-bonnet commented on jumanji/environments/combinatorial/cvrp/utils.py
> +    return jnp.linalg.norm((coordinates - jnp.roll(coordinates, -1, axis=0)), axis=1).sum()
Why are we summing potentially multiple norms here? I may be wrong here, but if we are given multiple coordinates and orders, we should expect multiple tour lengths and not the sum, right?

2022-10-05 15:20 UTC, clement-bonnet commented on jumanji/environments/combinatorial/utils.py
> +           problem: array of coordinates for all cities [problem_size, 2]
As `problem` is used in different contexts (just coordinates for TSP, coordinates and demands for CVRP), I would rename `problem` here as `coordinates` to make it clearer.

2022-10-05 16:37 UTC, merged